### ISSUE TITLE
Port to use 'stack' instead of 'stackage-build'

### ISSUE THREAD

**Issue by borsboom** [fpco/stackage-dot#1]
@mboes `stackage-build` is gone, so this can no longer be built.

**Comment by mboes** [comment]
We should probably also change the name of the binary, at this point. Do we have a naming scheme established for companion tools that build on top of Stack?

cc @snoyberg

**Comment by snoyberg** [comment]
I think stack-whatever

**Comment by mboes** [comment]
@snoyberg yes. What I was wondering is - does `stack-whatever` mean `stack whatever` works, the way `stackage whatever` used to? Or is that no longer the case?

**Comment by snoyberg** [comment]
Yes, @DanBurton ported the plugin mechanism over to stack.

**Comment by borsboom** [comment]
Something to consider: the plugin mechanism currently doesn't interact so well with Docker usage.  That is to say, if you run `stack dot` on the host, it'll require stack-dot to exist on the host even if docker use is enabled and stack-dot exists in the image.  And that stack-dot will be running on the host, not in the container (meaning it won't see the preinstalled libraries, tools, etc.).  So for Docker use you'd really need to run `stack exec stack-dot` which is kind of weird.

So is the current behaviour desirable, or should I open an issue to change it so plugins are searched for and run in a container if Docker is enabled?

**Comment by mboes** [comment]
@manny-fp let's continue that discussion in a separate ticket against the commercialhaskell/stack repo.

**Comment by rvion** [comment]
(copy paste of my comment here https://github.com/commercialhaskell/stack/issues/311 after suggestion of @manny-fp )

why don't we just move stackage-dot code in stack itself ?
- build-depends is really small(1)
- it will help mainting the tool
- it has already been done for at least one other stackage-*: cf87169
- I think that plugin system is a good idea for users' personnal scripts, but here, stack-dot would benefit everyone.
- people wanting to use docker base stack could add their own scripts on host calling stack --docker

(1) stackage-dot build depends:

```
   executable stackage-dot
     main-is:             Main.hs
     build-depends:       base >=4.7 && <4.8
                     , conduit >= 1.2
                     , conduit-combinators >= 0.3
                     , containers >= 0.5
                     , monad-logger >= 0.3
                     , stackage-build
                     , text >= 1.2
```

**Comment by snoyberg** [comment]
Based on discussion in commit, closing this.
